# Generated by Django 2.2.14 on 2020-07-31 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200727_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana_publicitaria',
            name='usuario_campana',
        ),
        migrations.AddField(
            model_name='campana_publicitaria',
            name='usuario_campana',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
