# Generated by Django 2.2.14 on 2020-07-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200730_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacion',
            old_name='ubicacion',
            new_name='red_social_ubicacion',
        ),
    ]
