# Generated by Django 2.2.14 on 2020-08-08 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200730_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='red_social_hashtag',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='red_social_ubicacion',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='red_social',
            name='hashtag_red_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hashtag'),
        ),
        migrations.AddField(
            model_name='red_social',
            name='ubicacion_red_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion'),
        ),
        migrations.RemoveField(
            model_name='campana_publicitaria',
            name='usuario_campana',
        ),
        migrations.AddField(
            model_name='campana_publicitaria',
            name='usuario_campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
